url: "mosca.net.br" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Blog do Mosca" # the name of your site, e.g. ACME Corp.

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "medicina"
      type: "posts"
    values:
      categories: ["medicina"]

permalink: /:year/:title/